site:
  title: Spring AI Watsonx.ai Documentation
  url: https://spring-ai-community.github.io/spring-ai-watsonx-ai
  start_page: spring-ai-watsonx-ai::index.adoc

content:
  sources:
    - url: ./../../../..
      branches: HEAD
      start_path: docs/src/main/antora

ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.17/ui-bundle.zip
    snapshot: true

asciidoc:
  attributes:
    page-pagination: true
    sectanchors: true
    sectlinks: true
    toc: left
    toclevels: 3
    idprefix: ''
    idseparator: '-'
