name: Publish version to Maven Central

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'              # Matches 1.0.0, 2.1.3
      - '[0-9]+.[0-9]+.[0-9]+-alpha.[0-9]+' # Matches 1.0.0-alpha.1
      - '[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'  # Matches 1.0.0-beta.1
      - '[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'    # Matches 1.0.0-rc.1
      - '[0-9]+.[0-9]+.[0-9]+-RC.[0-9]+'    # Matches 1.0.0-RC.1

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: central
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          
      - name: Build and Test
        run: mvn clean verify

      - name: Publish to Sonatype
        run: |
          mvn --batch-mode \
            -Prelease \
            -Pjavadoc \
            deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
